// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKTU9ZJV0jniub5FwXKDB0bqrNoYJESgM',
    appId: '1:242443416800:web:b4b7480943fd3b0fbb4c85',
    messagingSenderId: '242443416800',
    projectId: 'glucoguard-c24e3',
    authDomain: 'glucoguard-c24e3.firebaseapp.com',
    storageBucket: 'glucoguard-c24e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqXSmgkfo2ASL_dJrVgJsdL16ZnpbdF-4',
    appId: '1:242443416800:android:4402f3dcd4e5c26ebb4c85',
    messagingSenderId: '242443416800',
    projectId: 'glucoguard-c24e3',
    storageBucket: 'glucoguard-c24e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwkjwZtPZUovRZ22rAbXWzr20iCOfX7hE',
    appId: '1:242443416800:ios:6c3bfe2bf38d2adbbb4c85',
    messagingSenderId: '242443416800',
    projectId: 'glucoguard-c24e3',
    storageBucket: 'glucoguard-c24e3.firebasestorage.app',
    iosBundleId: 'com.example.interdisciplinary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwkjwZtPZUovRZ22rAbXWzr20iCOfX7hE',
    appId: '1:242443416800:ios:6c3bfe2bf38d2adbbb4c85',
    messagingSenderId: '242443416800',
    projectId: 'glucoguard-c24e3',
    storageBucket: 'glucoguard-c24e3.firebasestorage.app',
    iosBundleId: 'com.example.interdisciplinary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKTU9ZJV0jniub5FwXKDB0bqrNoYJESgM',
    appId: '1:242443416800:web:d028ff4d362b5e26bb4c85',
    messagingSenderId: '242443416800',
    projectId: 'glucoguard-c24e3',
    authDomain: 'glucoguard-c24e3.firebaseapp.com',
    storageBucket: 'glucoguard-c24e3.firebasestorage.app',
  );
}
